language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

install: composer update

script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-text tests
